name: Aggerbæk.dk

markdown: kramdown

lang: da

baseurl: ""

exclude: ["bower_components", "includes", "node_modules", "package.json", "gulpfile.js", "scss", "config.rb",
          "fbtest.html", "README.md", "Gemfile.*", "Vagrantfile"]

collections:
  albums:
    output: false
