
title: Aggerbaek.dk

baseurl: ""

# Language
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax-highlighter: rouge

lang: da


aaaurl: https://stavnstrup.github.io

exclude: ["vendor", "_assets", "Gemfile", "Gemfile.lock", "README.md", "node_modules", "package.json", "gulpfile.js",
          "scss", "Vagrantfile"]

collections:
  albums:
    output: false

# Gems:
