name: Aggerbæk.dk

markdown: kramdown

lang: da

baseurl: ""

exclude: ["README.md", "node_modules", "package.json", "gulpfile.js", "scss",
          "Gemfile", "Genfile.lock", "Vagrantfile"]

collections:
  albums:
    output: false
