name: Aggerbaek.dk

markdown: kramdown

lang: da

baseurl: ""


aaaurl: https://stavnstrup.github.io

exclude: ["README.md", "node_modules", "package.json", "gulpfile.js", "scss",
          "Gemfile", "Gemfile.lock", "Vagrantfile"]

collections:
  albums:
    output: false
